In [ ]:
!pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
a=np.ndarray([1,2,3])
print(a)

[[[1.45528770e-315 0.00000000e+000 2.52517499e-312]
  [2.41907520e-312 2.10077583e-312 6.84937801e-310]]]


In [ ]:
a=np.array([1,2,3 ])
print(a)

[1 2 3]


In [ ]:
b=np.array([[1,2,3],
            [4,5,6],
            ])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c=np.array([
            [
            [1,2],
            [3,4]
            ],
           [
            [7,8],
            [10,11]
            ]])

print(c)

[[[ 1  2]
  [ 3  4]]

 [[ 7  8]
  [10 11]]]


In [ ]:
d=np.zeros([3,3])
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
d=np.ones([3,3])
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
e=np.eye(3)
print()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
d=np.full([3,3],)
print(d)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [ ]:
def greet():
  """
  this is doc string
  """
  print("vishnu")
print(greet())
print(greet.__doc__)

vishnu
None

  this is doc string
  


In [ ]:
a=np.zeros([3,3])
b=np.ones([3,3],)
c=np.full([3,3],8)
d=np.eye(3)
print(a,b,c,d,"sep"="")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [[8 8 8]
 [8 8 8]
 [8 8 8]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
f=np.arange(2,10,3)
print(f)

[2 5 8]


In [ ]:
np.linspace(5,2,7)


array([5. , 4.5, 4. , 3.5, 3. , 2.5, 2. ])

In [ ]:
#uniform random
np.random.rand(3,3)

array([[ 0.9964285 , -1.28774876,  0.40021609],
       [ 0.16445939, -0.74668318,  0.56012622],
       [-0.428063  , -0.02724765, -1.22777634]])

In [ ]:
#normal distribution
np.random.randn(3,3)

array([[ 0.82487483,  0.87944227, -1.46110236],
       [-1.55790049, -0.62559417,  0.38720338],
       [ 0.22155945, -0.28781593,  0.80610964]])

In [ ]:
#random integers
np.random.randint(1,5,size=(4,4))

array([[1, 2, 4, 2],
       [4, 3, 1, 2],
       [1, 4, 2, 4],
       [2, 1, 2, 4]])

In [ ]:
#intialize (garbage value)
np.empty((2,4))

array([[4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323],
       [3.5e-323, 4.0e-323, 4.9e-323, 5.4e-323]])

In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

(2, 5)
2
10
int64
8
80


In [ ]:
arr=np.array([["a","b","c","d","e"]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

(1, 5)
2
5
<U1
4
20


In [ ]:
#indexing
a=np.array([10,20,30,40,50])
print(a[0])
print(a[-1])
print(a[0])
print(a[1:4])
print(a[1:4:2])
print(a[::2])

50
10
[20 30 40]
[20 40]
[10 30 50]


In [ ]:
#slicing
print(a[1:4])
print(a[:3])
print(a[::2])
print(a[::-1])

[20 30 40]
[10 20 30]
[10 30 50]
[50 40 30 20 10]


In [ ]:
#2d indexing
m=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

#single element(row,col)
print(m[0,0])
print(m[1,1])
#row slicing
print(m[0,:])
#column slicing
print(m[:,1])
#sub-matrix
print(m[0:2,1:3])

1
5
[1 2 3]
[2 5 8]
[[2 3]
 [5 6]]


In [ ]:
n=np.array([10,25,8,42,17])

#bolean task
mask= n > 20
print(mask)
print(n[mask])

#shorthand
print(n[n>20])

#fancyindexing
print(n[[0,3]])

[False  True False  True False]
[25 42]
[25 42]
[10 42]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)
print(a+10)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[11 12 13]


In [ ]:
h=np.array([1.5246,4.4586,9.1234,16.8954])
np.ceil(h)

array([ 2.,  5., 10., 17.])

In [ ]:
np.floor(h)

array([ 1.,  4.,  9., 16.])

In [ ]:
np.round(h,3)

array([ 1.525,  4.459,  9.123, 16.895])

In [ ]:
#1
arr=np.array([2,4,6,8,10,12,14,16,18,20])
print(arr)
np.max(a)

[ 2  4  6  8 10 12 14 16 18 20]


np.int64(2)

In [ ]:
#1
np.argmax(a)

np.int64(2)

In [ ]:
#2
l=np.eye(5,5)
print(l)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#2
np.reshape(l,(1,25))

array([[1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 1.]])

In [ ]:
#3
v=np.array([3,7,1,9,2,5,8,4])
print(v)

[3 7 1 9 2 5 8 4]


In [ ]:
#3
np.max(v)

np.int64(9)

In [ ]:
#3
np.argmax(v)

np.int64(3)

In [ ]:
#4
a=np.array([])
np.arange(2,4)

array([2, 3])

In [ ]:
#4
np.reshape(a,(3))

array([2, 3, 4])

In [ ]:
#5
m=np.array([1,2,3,4,5,10,20,30,40,50])
mask=m > 5
print(mask)
print(m[mask])

[False False False False False  True  True  True  True  True]
[10 20 30 40 50]


In [ ]:
#6
a=np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
          ])
b=np.array([[10,11,12],
          [13,14,15],
          [16,17,18]
          ])
np.random.rand()

0.4305239027414175

In [ ]:
#6
np.dot(a,b)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [ ]:
#7
 (arr-arr.min()/(arr.max()))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#8
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a,b)

[1 2 3] [4 5 6]


In [ ]:
#8
np.vstack(a)

array([[1],
       [2],
       [3]])

In [ ]:
#8
np.hstack(b)

array([4, 5, 6])

Data viuslization is a technique used to visualize/represnt the data as graphs,plots,charts